### ISSUE TITLE
SKYE NEEDS TO DO SOMETHING ASAP

### ISSUE THREAD

**Issue by NoahTarr** [Sphiinxx/MegaTravel#20]
Skye has not done ANYTHING on the website. I believe it is of the utmost importance to have her do ALLLLLLL the shitty fuckin work for not helping at all before state or regionals. MAKE HER get all the info we need and if she doesn't shes off the team! I will kick her off personaly if she doesnt make an effort to help us.

**Comment by mswdev** [comment]
Ok, I will make a list this weekend so we can get information on each location and some other stuff.
