### ISSUE TITLE
Packages - Main Packages

### ISSUE THREAD

**Issue by mswdev** [Sphiinxx/MegaTravel#4]
1. Change the Interactive Pricing.(FINISHED)
2. Finish the slideshow responsive.
3. Make the content below the slideshow responsive.(FINISHED)

**Comment by NoahTarr** [comment]
Interactive Pricing is finished.
Content below slideshow finished.

**Comment by NoahTarr** [comment]
I finished the 1 and 2. I am working on a lot of stuff so please finish the responsive matt!
